// Storyloom Unity Kit — game styles and the common player base.
// The kit can build three kinds of test scene from the same story: top-down (Stardew-style, the original), third person
// (camera behind the player, mouse / right stick to orbit) and first person (mouse look, crosshair). Interactables, the
// director and the UI are shared; only the player controller, camera and world plane differ.
using UnityEngine;

namespace Storyloom
{
    public enum GameStyle { TopDown = 0, ThirdPerson = 1, FirstPerson = 2 }

    /// <summary>Base for every kit player (2D top-down, 3D third person, 3D first person). Interactables and the director talk to this.</summary>
    public abstract class StoryloomPlayer : MonoBehaviour
    {
        public StoryloomKeyBinds keys;
        public static StoryloomPlayer Current { get; private set; }
        public abstract GameStyle Style { get; }
        /// <summary>True when the world lies on the XZ plane (3D styles); false for the XY top-down plane.</summary>
        public bool UsesXZ => Style != GameStyle.TopDown;
        public Interactable Focus { get; protected set; }
        public float NearestDistance { get; protected set; }
        public string NearestName { get; protected set; } = "";
        /// <summary>Centre-to-centre reach: the bind's radius plus room for the two bodies.</summary>
        public float Reach => (keys ? keys.interactRadius : 1.1f) + 1.1f;

        protected virtual void OnEnable() { Current = this; }
        protected virtual void OnDisable() { if (Current == this) Current = null; }
        protected bool InBeat => StoryloomDirector.Instance && StoryloomDirector.Instance.InBeat;
        protected bool InventoryOpen => StoryloomDirector.Instance && StoryloomDirector.Instance.inventoryHud && StoryloomDirector.Instance.inventoryHud.IsOpen;

        protected void SetFocus(Interactable best)
        {
            if (best == Focus) return;
            if (Focus) Focus.SetFocused(false);
            Focus = best;
            if (Focus) { Focus.SetFocused(true); StoryloomDirector.Note($"Focus → {Focus.name}{(Focus.prompt ? "" : " (no prompt object on it)")}"); }
        }
        /// <summary>Interact / inventory keys, shared by every style.</summary>
        protected void HandleActionKeys()
        {
            if (keys.InteractDown()) { if (InBeat) StoryloomDirector.Note("Interact pressed during a beat — ignored"); else if (Focus) { StoryloomDirector.Note($"Interact → {Focus.name} ({Focus.Verb})"); Focus.Interact(this); } else { StoryloomDirector.Note($"Interact: nothing in reach (nearest {NearestName} at {NearestDistance:0.0}, reach {Reach:0.0})"); if (StoryloomDirector.Instance && StoryloomDirector.Instance.dialogue) StoryloomDirector.Instance.dialogue.ShowBark("", "Nothing to interact with here.", null); } }
            if (keys.InventoryDown())
            {
                var d = StoryloomDirector.Instance; if (d && !d.inventoryHud) d.ResolveUI();
                if (d && d.inventoryHud) { d.inventoryHud.Toggle(); StoryloomDirector.Note("Inventory key → " + (d.inventoryHud.IsOpen ? "opened" : "closed")); }
                else { StoryloomDirector.Note("Inventory key pressed but no InventoryHUD in the scene"); Debug.LogWarning("Storyloom: inventory key pressed but the director has no InventoryHUD assigned"); }
            }
        }
    }

    /// <summary>Keeps a label (TextMesh) facing the camera. Used by the 3D placeholder prefabs.</summary>
    public class Billboard : MonoBehaviour
    {
        public bool yAxisOnly = false;
        void LateUpdate()
        {
            var cam = Camera.main; if (!cam) return;
            if (yAxisOnly) { var f = transform.position - cam.transform.position; f.y = 0; if (f.sqrMagnitude > 0.001f) transform.rotation = Quaternion.LookRotation(f); }
            else transform.rotation = Quaternion.LookRotation(transform.position - cam.transform.position, cam.transform.up);
        }
    }

    /// <summary>Marks a prefab generated by the kit for a given style, so "Create scene" can swap placeholders when the style changes without touching your own prefabs.</summary>
    public class StoryloomPlaceholder : MonoBehaviour { public GameStyle style; }

    /// <summary>Locks the mouse while free-roaming in the 3D styles; releases it during beats, with the inventory open, or after Cancel (click to grab it again).</summary>
    public class CursorLock : MonoBehaviour
    {
        public StoryloomKeyBinds keys; public bool enabledLock = true; bool _released;
        void Update()
        {
            if (!enabledLock) { Cursor.lockState = CursorLockMode.None; Cursor.visible = true; return; }
            var d = StoryloomDirector.Instance;
            bool busy = (d && d.InBeat) || (d && d.inventoryHud && d.inventoryHud.IsOpen);
            if (keys && keys.CancelDown() && !busy) _released = true;
            if (_released && !busy && keys && keys.AdvanceDown()) _released = false;   // click / interact grabs the mouse again
            bool free = !busy && !_released;
            Cursor.lockState = free ? CursorLockMode.Locked : CursorLockMode.None; Cursor.visible = !free;
        }
        void OnDisable() { Cursor.lockState = CursorLockMode.None; Cursor.visible = true; }
    }
}
